//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.ACCOUNT_BANK_ACCOUNTS_ERP = new HashSet<ACCOUNT_BANK_ACCOUNTS_ERP>();
            this.ACCOUNT_SECTION_ERP = new HashSet<ACCOUNT_SECTION_ERP>();
            this.ACCOUNT1 = new HashSet<ACCOUNT>();
            this.TRANS = new HashSet<TRANS>();
            this.BUDGETS_ACCOUNT_ERP = new HashSet<BUDGETS_ACCOUNT_ERP>();
            this.CHEQUES_DATA_ERP = new HashSet<CHEQUES_DATA_ERP>();
            this.STAKEHOLDERS_ACCOUNTS_ERP = new HashSet<STAKEHOLDERS_ACCOUNTS_ERP>();
            this.CRNOTES_DTL_ERP = new HashSet<CRNOTES_DTL_ERP>();
            this.CRNOTES_MAS_ERP = new HashSet<CRNOTES_MAS_ERP>();
            this.FUND = new HashSet<FUND>();
            this.FUND1 = new HashSet<FUND>();
            this.JOURNAL_DETAILS = new HashSet<JOURNAL_DETAILS>();
            this.COLLECTORS_BOXES_ERP = new HashSet<COLLECTORS_BOXES_ERP>();
            this.ACCOUNT_BANK_ERP = new HashSet<ACCOUNT_BANK_ERP>();
            this.UNITS_ACCOUNTS_ERP = new HashSet<UNITS_ACCOUNTS_ERP>();
            this.DRNOTES_DTL_ERP = new HashSet<DRNOTES_DTL_ERP>();
            this.DRNOTES_MAS_ERP = new HashSet<DRNOTES_MAS_ERP>();
            this.PYVC_DTL_ERP = new HashSet<PYVC_DTL_ERP>();
            this.PYVC_ERP = new HashSet<PYVC_ERP>();
            this.RCVC_DTL_ERP = new HashSet<RCVC_DTL_ERP>();
            this.RCVC_ERP = new HashSet<RCVC_ERP>();
            this.DEPOSIT_BANK_DTL_ERP = new HashSet<DEPOSIT_BANK_DTL_ERP>();
            this.DEPOSIT_BANK_ERP = new HashSet<DEPOSIT_BANK_ERP>();
            this.ILTIZAM_DETAILS = new HashSet<ILTIZAM_DETAILS>();
            this.ILTIZAM = new HashSet<ILTIZAM>();
            this.DEPOSIT_BANK_ERP1 = new HashSet<DEPOSIT_BANK_ERP>();
        }
    
        public string ACCOUNT_NO { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string BELONGTO { get; set; }
        public Nullable<decimal> ACCOUNT_LEVEL { get; set; }
        public string SORTCRITERIA { get; set; }
        public Nullable<decimal> NUMBERBELOW { get; set; }
        public string ACCOUNT_ENAME { get; set; }
        public string FUND_CODE { get; set; }
        public string FS_CODE { get; set; }
        public string FN_CODE { get; set; }
        public string PR_CODE { get; set; }
        public string SC_CODE { get; set; }
        public string CC { get; set; }
        public string TYPEOFACCOUNT { get; set; }
        public string ACTIVE { get; set; }
        public string MAAREF { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public string ACCTYPE_LEVEL1 { get; set; }
        public string MOLGNUMBER { get; set; }
        public Nullable<decimal> SORT_INDEX { get; set; }
        public string IS_ACCOUNT_REF { get; set; }
        public string CAT { get; set; }
        public string LEVEL3_CODE { get; set; }
        public string REF_TYPE { get; set; }
        public Nullable<decimal> EXPENSE_CAT_ID { get; set; }
        public string NEW_ACCOUNT_NO { get; set; }
        public Nullable<decimal> SYS_STS__787BX4M1EVDGWJ88ZX8OB { get; set; }
        public Nullable<decimal> SYS_STSTRZ6J6W2BS6ZLYJXYLZSPA_ { get; set; }
        public Nullable<decimal> SYS_STSVZQFNVI3Z7QT__0LB1K1W77 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_BANK_ACCOUNTS_ERP> ACCOUNT_BANK_ACCOUNTS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_SECTION_ERP> ACCOUNT_SECTION_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNT1 { get; set; }
        public virtual ACCOUNT ACCOUNT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANS> TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUDGETS_ACCOUNT_ERP> BUDGETS_ACCOUNT_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEQUES_DATA_ERP> CHEQUES_DATA_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAKEHOLDERS_ACCOUNTS_ERP> STAKEHOLDERS_ACCOUNTS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_DTL_ERP> CRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_MAS_ERP> CRNOTES_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUND> FUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUND> FUND1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_DETAILS> JOURNAL_DETAILS { get; set; }
        public virtual LEVEL3 LEVEL3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLLECTORS_BOXES_ERP> COLLECTORS_BOXES_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_BANK_ERP> ACCOUNT_BANK_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_ACCOUNTS_ERP> UNITS_ACCOUNTS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_DTL_ERP> DRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_MAS_ERP> DRNOTES_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_DTL_ERP> PYVC_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_ERP> PYVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_DTL_ERP> RCVC_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_ERP> RCVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_BANK_DTL_ERP> DEPOSIT_BANK_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_BANK_ERP> DEPOSIT_BANK_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_DETAILS> ILTIZAM_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM> ILTIZAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_BANK_ERP> DEPOSIT_BANK_ERP1 { get; set; }
    }
}
