//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGETS_ACCOUNT_ERP
    {
        public decimal ID { get; set; }
        public decimal FY_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string FUND_CODE { get; set; }
        public Nullable<decimal> F_READ { get; set; }
        public Nullable<decimal> S_READ { get; set; }
        public Nullable<decimal> TH_READ { get; set; }
        public Nullable<decimal> FINAL_READ { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual FUND FUND { get; set; }
    }
}
