//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLLERS_TABLE_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTROLLERS_TABLE_ERP()
        {
            this.VIEWS = new HashSet<VIEWS>();
        }
    
        public string CONTROLLER_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string METHOD_NAME { get; set; }
        public decimal ID { get; set; }
        public string ON_MENU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIEWS> VIEWS { get; set; }
    }
}
