//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRNOTES_DTL_ERP
    {
        public decimal ID { get; set; }
        public decimal CRNOTE_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string CC { get; set; }
        public decimal AMT { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
        public string FUND_CODE { get; set; }
        public string UNIT_ID { get; set; }
        public string FUND_TYPE { get; set; }
        public Nullable<decimal> PR_CODE { get; set; }
        public Nullable<decimal> FS_CODE { get; set; }
        public Nullable<decimal> STAKEHOLDER_ID { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
        public Nullable<decimal> BOX_ID { get; set; }
        public Nullable<decimal> BANK_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ACCOUNT_BANK_ERP ACCOUNT_BANK_ERP { get; set; }
        public virtual COLLECTORS_BOXES_ERP COLLECTORS_BOXES_ERP { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual CRNOTES_MAS_ERP CRNOTES_MAS_ERP { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP { get; set; }
        public virtual EMPLOYEE_HERP EMPLOYEE_HERP { get; set; }
        public virtual FUNDERS_ERP FUNDERS_ERP { get; set; }
        public virtual UNITS_ERP UNITS_ERP { get; set; }
        public virtual FUND FUND { get; set; }
    }
}
