//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSIT_ATTACHMENTS_ERP
    {
        public decimal ID { get; set; }
        public string TITLE { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] LOB_FILE { get; set; }
        public Nullable<decimal> DEPOSIT_BANK_ID { get; set; }
    
        public virtual DEPOSIT_BANK_ERP DEPOSIT_BANK_ERP { get; set; }
    }
}
