//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSIT_BANK_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPOSIT_BANK_ERP()
        {
            this.DEPOSIT_ATTACHMENTS_ERP = new HashSet<DEPOSIT_ATTACHMENTS_ERP>();
            this.DEPOSIT_BANK_DTL_ERP = new HashSet<DEPOSIT_BANK_DTL_ERP>();
            this.DEPOSIT_WK_ERP = new HashSet<DEPOSIT_WK_ERP>();
        }
    
        public decimal ID { get; set; }
        public string STATUS { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string ENTRY_BY { get; set; }
        public string ACCOUNT_NO { get; set; }
        public Nullable<decimal> REF_ID { get; set; }
        public string FUND_CODE { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public string SC { get; set; }
        public string FN { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
        public string PR { get; set; }
        public string CC { get; set; }
        public string DEPOSIT_METHOD { get; set; }
        public Nullable<decimal> REVERSE_NO { get; set; }
        public string REVERSE_REASON { get; set; }
        public string ACCOUNT_NO2 { get; set; }
        public string FUND_CODE2 { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ACCOUNT ACCOUNT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_ATTACHMENTS_ERP> DEPOSIT_ATTACHMENTS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_BANK_DTL_ERP> DEPOSIT_BANK_DTL_ERP { get; set; }
        public virtual FUND FUND { get; set; }
        public virtual FN FN1 { get; set; }
        public virtual PR PR1 { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_WK_ERP> DEPOSIT_WK_ERP { get; set; }
        public virtual FUND FUND1 { get; set; }
        public virtual JOURNAL JOURNAL { get; set; }
    }
}
