//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPT_ERP()
        {
            this.EMPLOYEE_HERP = new HashSet<EMPLOYEE_HERP>();
            this.SECTIONS_ERP = new HashSet<SECTIONS_ERP>();
        }
    
        public string ID { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
        public string IS_VALID { get; set; }
        public string MANAGER_ID { get; set; }
        public string ENTRY_PLAN_ID { get; set; }
        public string ACCEPTED { get; set; }
        public string CONFIRMED { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
        public string CC_CODE_IFMIS { get; set; }
        public Nullable<decimal> SECTION_ID_IFMIS { get; set; }
        public Nullable<decimal> SYS_STSAFA__SKREI18MQWGGUI8K8U { get; set; }
    
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        public virtual STAFF_ERP STAFF_ERP1 { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_HERP> EMPLOYEE_HERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECTIONS_ERP> SECTIONS_ERP { get; set; }
    }
}
