//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRNOTES_MAS_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRNOTES_MAS_ERP()
        {
            this.DRNOTES_DTL_ERP = new HashSet<DRNOTES_DTL_ERP>();
            this.DRNOTES_WK_ERP = new HashSet<DRNOTES_WK_ERP>();
            this.ILTIZAM_ATTACHMENTS_ERP = new HashSet<ILTIZAM_ATTACHMENTS_ERP>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string ENTRY_BY { get; set; }
        public string STATUS { get; set; }
        public string ACCOUNT_NO { get; set; }
        public Nullable<decimal> STAKEHOLDER_ID { get; set; }
        public string FUND_CODE { get; set; }
        public string NOTES { get; set; }
        public string CURN { get; set; }
        public Nullable<decimal> FCRATE { get; set; }
        public Nullable<decimal> REVERSE_NO { get; set; }
        public string REVERSE_REASON { get; set; }
        public Nullable<decimal> AMT_PAID { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CURN CURN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_DTL_ERP> DRNOTES_DTL_ERP { get; set; }
        public virtual FUND FUND { get; set; }
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_WK_ERP> DRNOTES_WK_ERP { get; set; }
        public virtual EMPLOYEE_HERP EMPLOYEE_HERP { get; set; }
        public virtual JOURNAL JOURNAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_ATTACHMENTS_ERP> ILTIZAM_ATTACHMENTS_ERP { get; set; }
    }
}
