//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_HERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE_HERP()
        {
            this.CRNOTES_DTL_ERP = new HashSet<CRNOTES_DTL_ERP>();
            this.CRNOTES_MAS_ERP = new HashSet<CRNOTES_MAS_ERP>();
            this.EMPLOYEE_HERP1 = new HashSet<EMPLOYEE_HERP>();
            this.JOURNAL_DETAILS = new HashSet<JOURNAL_DETAILS>();
            this.STAFF_ERP = new HashSet<STAFF_ERP>();
            this.STAKEHOLDER_EMPLOYEES_ERP = new HashSet<STAKEHOLDER_EMPLOYEES_ERP>();
            this.DRNOTES_DTL_ERP = new HashSet<DRNOTES_DTL_ERP>();
            this.DRNOTES_MAS_ERP = new HashSet<DRNOTES_MAS_ERP>();
            this.PYVC_ERP = new HashSet<PYVC_ERP>();
            this.RCVC_ERP = new HashSet<RCVC_ERP>();
            this.ILTIZAM = new HashSet<ILTIZAM>();
        }
    
        public decimal ID { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
        public string IDNO { get; set; }
        public string PASSPORTNO { get; set; }
        public string ADDL1 { get; set; }
        public string ADDL2 { get; set; }
        public Nullable<decimal> REGION_ID { get; set; }
        public string TELEPHONE { get; set; }
        public string MOBILE { get; set; }
        public string FAX { get; set; }
        public string E_MAIL { get; set; }
        public string SEX { get; set; }
        public Nullable<decimal> MARITAL_STATUS_ID { get; set; }
        public Nullable<decimal> CURRENT_STATUS_ID { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string DEPT_ID { get; set; }
        public string SECTION_ID { get; set; }
        public string UNIT_ID { get; set; }
        public byte[] EMPLOYEE_PIC { get; set; }
        public string IS_VALID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string JOB_NUMBER { get; set; }
        public Nullable<decimal> ATTENDANCE_EMP_NO { get; set; }
        public Nullable<decimal> EMPLOYMENT_ID { get; set; }
        public Nullable<decimal> POSITION_CLASS_ID { get; set; }
        public Nullable<decimal> POSITION_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> EMPLOYMENT_DATE { get; set; }
        public Nullable<System.DateTime> CLASS_DATE { get; set; }
        public Nullable<decimal> CERTIFICATE_ID { get; set; }
        public Nullable<decimal> ACTUAL_YEARS { get; set; }
        public string BANK_TRANSFER { get; set; }
        public Nullable<decimal> BANK_ID { get; set; }
        public Nullable<decimal> BRANCH_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public Nullable<decimal> EMPLOYMENT_SALARY { get; set; }
        public string GRADE_ID { get; set; }
        public Nullable<decimal> STEP_ID { get; set; }
        public Nullable<decimal> NO_OF_CHILDREN { get; set; }
        public Nullable<decimal> NO_CHILDREN_UNIVERSITY { get; set; }
        public Nullable<decimal> DIFF_AMT { get; set; }
        public Nullable<decimal> SHIFT_WORK_ID { get; set; }
        public Nullable<decimal> GROUP_ID { get; set; }
        public Nullable<decimal> DAILY_AMT { get; set; }
        public Nullable<decimal> RETIREMENT_AMT { get; set; }
        public Nullable<System.DateTime> RETIREMENT_DATE { get; set; }
        public Nullable<System.DateTime> CONTRACT_START_DATE { get; set; }
        public Nullable<System.DateTime> CONTRACT_END_DATE { get; set; }
        public Nullable<decimal> CONTRACT_AMT { get; set; }
        public Nullable<decimal> SUPERVISOR { get; set; }
        public Nullable<decimal> PAYREC_CODE { get; set; }
        public Nullable<decimal> BASIC_SALARY { get; set; }
        public string POSTED { get; set; }
        public string MUN_JAWWAL { get; set; }
        public string BLOOD_TYPE { get; set; }
        public string TEL_EXTENSION { get; set; }
        public string FILE_NAME { get; set; }
        public string TRANSPORT_EXEMPTION { get; set; }
        public string INTEREST { get; set; }
        public string HOUSING_EXEMPTION { get; set; }
        public string UNDER_TEST { get; set; }
        public Nullable<System.DateTime> UNDER_TEST_FDATE { get; set; }
        public Nullable<System.DateTime> UNDER_TEST_TOTDATE { get; set; }
        public string NEED_DRIVING_LICENSE { get; set; }
        public Nullable<System.DateTime> LICENSE_EXPIRATION_DATE { get; set; }
        public Nullable<System.DateTime> BEGINNING_HEALTH_INSURANCE { get; set; }
        public string TAX_ON { get; set; }
        public string RETIREMENT_TYPE { get; set; }
        public Nullable<decimal> EVAL_ID { get; set; }
        public Nullable<decimal> VAC_BALANCE { get; set; }
        public Nullable<decimal> VAC_SICK_BALANCE { get; set; }
        public Nullable<decimal> LEAVE_HOURS { get; set; }
        public string FUND_ID { get; set; }
        public Nullable<decimal> FILE_NO { get; set; }
        public Nullable<decimal> RETIREMENT_SAL { get; set; }
        public string IS_STUDENT { get; set; }
        public Nullable<decimal> REF_BANK_ID { get; set; }
        public string HAS_COMMITEE { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> WORK_START_TIME { get; set; }
        public Nullable<System.DateTime> WORK_END_TIME { get; set; }
        public Nullable<System.DateTime> RET_CONTRIBUTION_DATE { get; set; }
        public string IS_SUNDAY { get; set; }
        public string IS_FRIDAY { get; set; }
        public string IS_CLOCK { get; set; }
        public string OFFICE_NO { get; set; }
        public string FIRST_TIME_CLOCK_PROBLEM { get; set; }
        public Nullable<decimal> OVER_TIME { get; set; }
        public Nullable<decimal> PREV_RET_AMT { get; set; }
        public Nullable<decimal> PREV_SAVING_AMT { get; set; }
        public Nullable<decimal> ABSENCE_DAYS { get; set; }
        public Nullable<decimal> JAWAL_AMT { get; set; }
        public string IS_SBITANY { get; set; }
        public string LEAVE_WORK_REASON { get; set; }
        public Nullable<System.DateTime> LEAVE_WORK_DATE { get; set; }
        public string CLOCK_CODE { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public string NO_SALARY { get; set; }
        public Nullable<decimal> PENDING_STATUS_ID { get; set; }
        public Nullable<decimal> LICENSE_TYPE_ID { get; set; }
        public Nullable<System.DateTime> LICENSE_START_DATE { get; set; }
        public byte[] LICENSE_PIC { get; set; }
        public string RESIGN_PAID { get; set; }
        public string IS_FIELD { get; set; }
        public Nullable<decimal> CLOCK_LOCATION_ID { get; set; }
        public string SALARY { get; set; }
        public Nullable<System.DateTime> END_OF_PROBATIONARY_PERIOD { get; set; }
        public Nullable<decimal> PLACE_OF_BIRTH { get; set; }
    
        public virtual ACCOUNT_BANK_ERP ACCOUNT_BANK_ERP { get; set; }
        public virtual BANK_HERP BANK_HERP { get; set; }
        public virtual BRANCH_HERP BRANCH_HERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_DTL_ERP> CRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_MAS_ERP> CRNOTES_MAS_ERP { get; set; }
        public virtual DEPT_ERP DEPT_ERP { get; set; }
        public virtual SECTIONS_ERP SECTIONS_ERP { get; set; }
        public virtual UNITS_ERP UNITS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_HERP> EMPLOYEE_HERP1 { get; set; }
        public virtual EMPLOYEE_HERP EMPLOYEE_HERP2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_DETAILS> JOURNAL_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAFF_ERP> STAFF_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAKEHOLDER_EMPLOYEES_ERP> STAKEHOLDER_EMPLOYEES_ERP { get; set; }
        public virtual FUND FUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_DTL_ERP> DRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_MAS_ERP> DRNOTES_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_ERP> PYVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_ERP> RCVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM> ILTIZAM { get; set; }
    }
}
