//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIXED_PRINT_ERP
    {
        public byte[] H1 { get; set; }
        public byte[] H2 { get; set; }
        public byte[] H3 { get; set; }
        public byte[] FOOTER { get; set; }
        public decimal ID { get; set; }
        public string MUNICIPALITY_NAME_AR { get; set; }
        public string MUNICIPALITY_NAME_EN { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string URL_API { get; set; }
        public byte[] HEADER_OSS { get; set; }
        public string SMS_API { get; set; }
    }
}
