//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FS()
        {
            this.ILTIZAM = new HashSet<ILTIZAM>();
        }
    
        public string FS_CODE { get; set; }
        public string FS_NAME { get; set; }
        public string FS_ENAME { get; set; }
        public string SHOW { get; set; }
        public Nullable<decimal> FS_GROUP_ID { get; set; }
    
        public virtual FS_GROUP_ERP FS_GROUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM> ILTIZAM { get; set; }
    }
}
