//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNDERS_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNDERS_ERP()
        {
            this.CRNOTES_DTL_ERP = new HashSet<CRNOTES_DTL_ERP>();
            this.JOURNAL_DETAILS = new HashSet<JOURNAL_DETAILS>();
            this.TRANS = new HashSet<TRANS>();
            this.DRNOTES_DTL_ERP = new HashSet<DRNOTES_DTL_ERP>();
            this.RCVC_ERP = new HashSet<RCVC_ERP>();
            this.ILTIZAM_DETAILS = new HashSet<ILTIZAM_DETAILS>();
        }
    
        public decimal ID { get; set; }
        public string FUNDER_CODE { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
        public string IS_VALID { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string COUNTRY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_DTL_ERP> CRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_DETAILS> JOURNAL_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANS> TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_DTL_ERP> DRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_ERP> RCVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_DETAILS> ILTIZAM_DETAILS { get; set; }
    }
}
