//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPS_ERP()
        {
            this.CRNOTES_WKSETUP_ERP = new HashSet<CRNOTES_WKSETUP_ERP>();
            this.CRNOTES_WKSETUP_ERP1 = new HashSet<CRNOTES_WKSETUP_ERP>();
            this.DRNOTES_WKSETUP_ERP = new HashSet<DRNOTES_WKSETUP_ERP>();
            this.GROUPS_STAFF_ERP = new HashSet<GROUPS_STAFF_ERP>();
            this.JOURNAL_WKSETUP_ERP = new HashSet<JOURNAL_WKSETUP_ERP>();
            this.RCVC_WKSETUP_ERP = new HashSet<RCVC_WKSETUP_ERP>();
            this.DEPOSIT_WKSETUP_ERP = new HashSet<DEPOSIT_WKSETUP_ERP>();
            this.ILTIZAM_WKSETUP_ERP = new HashSet<ILTIZAM_WKSETUP_ERP>();
            this.PYVC_WKSETUP_ERP = new HashSet<PYVC_WKSETUP_ERP>();
            this.GROUP_MODULES = new HashSet<GROUP_MODULES>();
            this.CONTROLLERS_GROUPS_ERP = new HashSet<CONTROLLERS_GROUPS_ERP>();
        }
    
        public decimal ID { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_WKSETUP_ERP> CRNOTES_WKSETUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_WKSETUP_ERP> CRNOTES_WKSETUP_ERP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_WKSETUP_ERP> DRNOTES_WKSETUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_STAFF_ERP> GROUPS_STAFF_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_WKSETUP_ERP> JOURNAL_WKSETUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_WKSETUP_ERP> RCVC_WKSETUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_WKSETUP_ERP> DEPOSIT_WKSETUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_WKSETUP_ERP> ILTIZAM_WKSETUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_WKSETUP_ERP> PYVC_WKSETUP_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_MODULES> GROUP_MODULES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROLLERS_GROUPS_ERP> CONTROLLERS_GROUPS_ERP { get; set; }
    }
}
