//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILTIZAM_DETAILS
    {
        public decimal ILTIZAM_NO { get; set; }
        public string FUND_CODE { get; set; }
        public string FN_CODE { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string CC_CODE { get; set; }
        public string SC_CODE { get; set; }
        public decimal CURNDBAMT { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
        public string UNIT_ID { get; set; }
        public string FUND_TYPE { get; set; }
        public Nullable<decimal> PR_CODE { get; set; }
        public Nullable<decimal> FS_CODE { get; set; }
        public Nullable<decimal> CAR_NO { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual FN FN { get; set; }
        public virtual FUND FUND { get; set; }
        public virtual FUNDERS_ERP FUNDERS_ERP { get; set; }
        public virtual ILTIZAM ILTIZAM { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual UNITS_ERP UNITS_ERP { get; set; }
    }
}
