//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILTIZAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILTIZAM()
        {
            this.ILTIZAM_DETAILS = new HashSet<ILTIZAM_DETAILS>();
            this.ILTIZAM_WK_ERP = new HashSet<ILTIZAM_WK_ERP>();
            this.ILTIZAM_ATTACHMENTS_ERP = new HashSet<ILTIZAM_ATTACHMENTS_ERP>();
        }
    
        public decimal ILTIZAM_NO { get; set; }
        public Nullable<System.DateTime> ILTIZAM_DATE { get; set; }
        public string DETAILS { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string ESANAD_NO { get; set; }
        public Nullable<System.DateTime> ESANAD_DATE { get; set; }
        public string MAJLES_NO { get; set; }
        public Nullable<System.DateTime> MAJLES_DATE { get; set; }
        public string NOTES { get; set; }
        public string CFUND_CODE { get; set; }
        public string CFS_CODE { get; set; }
        public string CFN_CODE { get; set; }
        public string CACCOUNT_NO { get; set; }
        public string CCC_CODE { get; set; }
        public string CPR_CODE { get; set; }
        public string CSC_CODE { get; set; }
        public Nullable<decimal> INSANAD_NUMBER { get; set; }
        public string MANUAL_NO { get; set; }
        public string WASF { get; set; }
        public Nullable<decimal> STAKEHOLDER_ID { get; set; }
        public string STATUS { get; set; }
        public string CURN_CODE { get; set; }
        public Nullable<decimal> FCRATE { get; set; }
        public string ENTRY_BY { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public string CANCEL_BY { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string RESERVED_BY { get; set; }
        public Nullable<System.DateTime> RESERVED_DATE { get; set; }
        public string RESERVED_NOTES { get; set; }
        public string CANCEL_NOTES { get; set; }
        public Nullable<System.DateTime> INSANAD_DATE { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
        public Nullable<decimal> AMT_PAID { get; set; }
        public string HAS_DISCOUNT { get; set; }
        public Nullable<decimal> DISCOUNT_AMT { get; set; }
        public string REVERSE_REASON { get; set; }
        public Nullable<decimal> REVERSE_NO { get; set; }
        public Nullable<decimal> TAX_DISCOUNT { get; set; }
        public Nullable<decimal> DIR_PURCH_ID { get; set; }
        public Nullable<decimal> DIR_PURCH_SERV_ID { get; set; }
        public Nullable<decimal> SYS_STS04JYN2U_HYQ1U__S5GBFIKV { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CURN CURN { get; set; }
        public virtual EMPLOYEE_HERP EMPLOYEE_HERP { get; set; }
        public virtual FN FN { get; set; }
        public virtual FS FS { get; set; }
        public virtual FUND FUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_DETAILS> ILTIZAM_DETAILS { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP { get; set; }
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        public virtual PR PR { get; set; }
        public virtual STAFF_ERP STAFF_ERP1 { get; set; }
        public virtual STAFF_ERP STAFF_ERP2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_WK_ERP> ILTIZAM_WK_ERP { get; set; }
        public virtual JOURNAL JOURNAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_ATTACHMENTS_ERP> ILTIZAM_ATTACHMENTS_ERP { get; set; }
    }
}
