//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOURNAL()
        {
            this.CRNOTES_MAS_ERP = new HashSet<CRNOTES_MAS_ERP>();
            this.JOURNAL_DETAILS = new HashSet<JOURNAL_DETAILS>();
            this.JOURNAL_WK_ERP = new HashSet<JOURNAL_WK_ERP>();
            this.JOURNAL1 = new HashSet<JOURNAL>();
            this.DRNOTES_MAS_ERP = new HashSet<DRNOTES_MAS_ERP>();
            this.RCVC_ERP = new HashSet<RCVC_ERP>();
            this.PYVC_ERP = new HashSet<PYVC_ERP>();
            this.DEPOSIT_BANK_ERP = new HashSet<DEPOSIT_BANK_ERP>();
            this.ILTIZAM = new HashSet<ILTIZAM>();
            this.ILTIZAM_ATTACHMENTS_ERP = new HashSet<ILTIZAM_ATTACHMENTS_ERP>();
        }
    
        public decimal JOURNAL_NO { get; set; }
        public Nullable<System.DateTime> JOURNAL_DATE { get; set; }
        public string DETAILS { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> REVERSAL_NO { get; set; }
        public string REVERSAL_NOTES { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public string REVERSAL_BY { get; set; }
        public Nullable<System.DateTime> REVERSAL_DATE { get; set; }
        public string CANCEL_BY { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string ENTRY_BY { get; set; }
        public Nullable<decimal> JOURNAL_TYPE_ID { get; set; }
        public Nullable<decimal> REVERSE_NO { get; set; }
        public string REVERSE_REASON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_MAS_ERP> CRNOTES_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_DETAILS> JOURNAL_DETAILS { get; set; }
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        public virtual STAFF_ERP STAFF_ERP1 { get; set; }
        public virtual JOURNAL_TYPES_ERP JOURNAL_TYPES_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_WK_ERP> JOURNAL_WK_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL> JOURNAL1 { get; set; }
        public virtual JOURNAL JOURNAL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_MAS_ERP> DRNOTES_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_ERP> RCVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_ERP> PYVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_BANK_ERP> DEPOSIT_BANK_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM> ILTIZAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_ATTACHMENTS_ERP> ILTIZAM_ATTACHMENTS_ERP { get; set; }
    }
}
