//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEVEL2()
        {
            this.LEVEL3 = new HashSet<LEVEL3>();
        }
    
        public string LEVEL2_CODE { get; set; }
        public string LEVEL1_CODE { get; set; }
        public string A_NAME { get; set; }
        public string E_NAME { get; set; }
        public string MOLG_ID { get; set; }
        public Nullable<decimal> SYS_STST96X_46Z0JUVU_3J_8XPC0D { get; set; }
    
        public virtual LEVEL1 LEVEL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEVEL3> LEVEL3 { get; set; }
    }
}
