//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUN_CLASS_MAS_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUN_CLASS_MAS_ERP()
        {
            this.MUN_CLASS_DTL_ERP = new HashSet<MUN_CLASS_DTL_ERP>();
        }
    
        public string CODE { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
        public Nullable<decimal> SEQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUN_CLASS_DTL_ERP> MUN_CLASS_DTL_ERP { get; set; }
    }
}
