//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUN_CLASS_DTL_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUN_CLASS_DTL_ERP()
        {
            this.ACCOUNT_SECTION_ERP = new HashSet<ACCOUNT_SECTION_ERP>();
            this.BUDGETS_ACCOUNT_ERP = new HashSet<BUDGETS_ACCOUNT_ERP>();
            this.CRNOTES_DTL_ERP = new HashSet<CRNOTES_DTL_ERP>();
            this.DEPT_ERP = new HashSet<DEPT_ERP>();
            this.JOURNAL_DETAILS = new HashSet<JOURNAL_DETAILS>();
            this.UNITS_ERP = new HashSet<UNITS_ERP>();
            this.TRANS = new HashSet<TRANS>();
            this.DRNOTES_DTL_ERP = new HashSet<DRNOTES_DTL_ERP>();
            this.PYVC_DTL_ERP = new HashSet<PYVC_DTL_ERP>();
            this.PYVC_ERP = new HashSet<PYVC_ERP>();
            this.RCVC_DTL_ERP = new HashSet<RCVC_DTL_ERP>();
            this.RCVC_ERP = new HashSet<RCVC_ERP>();
            this.DEPOSIT_BANK_ERP = new HashSet<DEPOSIT_BANK_ERP>();
            this.ILTIZAM_DETAILS = new HashSet<ILTIZAM_DETAILS>();
        }
    
        public decimal ID { get; set; }
        public string MUN_CLASS_CODE { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_SECTION_ERP> ACCOUNT_SECTION_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUDGETS_ACCOUNT_ERP> BUDGETS_ACCOUNT_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_DTL_ERP> CRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPT_ERP> DEPT_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_DETAILS> JOURNAL_DETAILS { get; set; }
        public virtual MUN_CLASS_MAS_ERP MUN_CLASS_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_ERP> UNITS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANS> TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_DTL_ERP> DRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_DTL_ERP> PYVC_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_ERP> PYVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_DTL_ERP> RCVC_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_ERP> RCVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSIT_BANK_ERP> DEPOSIT_BANK_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_DETAILS> ILTIZAM_DETAILS { get; set; }
    }
}
