//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYVC_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PYVC_ERP()
        {
            this.PYVC_ATTACHMENTS_ERP = new HashSet<PYVC_ATTACHMENTS_ERP>();
            this.PYVC_DTL_ERP = new HashSet<PYVC_DTL_ERP>();
            this.PYVC_WK_ERP = new HashSet<PYVC_WK_ERP>();
        }
    
        public decimal ID { get; set; }
        public string STATUS { get; set; }
        public string ACCOUNT_NO { get; set; }
        public Nullable<decimal> STAKEHOLDER_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string ENTRY_BY { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public string FUND_CODE { get; set; }
        public string CURN { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
        public string CC { get; set; }
        public string PR { get; set; }
        public string FN { get; set; }
        public string SC { get; set; }
        public string PAY_FOR { get; set; }
        public string REF_MANUAL { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
        public Nullable<decimal> ILTIZAM_AMT { get; set; }
        public string IDNO { get; set; }
        public string DISCOUNT_TYPE { get; set; }
        public Nullable<decimal> DISCOUNT_AMT { get; set; }
        public Nullable<decimal> REVERSE_NO { get; set; }
        public string REVERSE_REASON { get; set; }
        public Nullable<decimal> STAKEHOLDER2 { get; set; }
        public Nullable<decimal> GLTAX_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CURN CURN1 { get; set; }
        public virtual EMPLOYEE_HERP EMPLOYEE_HERP { get; set; }
        public virtual FN FN1 { get; set; }
        public virtual FUND FUND { get; set; }
        public virtual JOURNAL JOURNAL { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual PR PR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_ATTACHMENTS_ERP> PYVC_ATTACHMENTS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_DTL_ERP> PYVC_DTL_ERP { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_WK_ERP> PYVC_WK_ERP { get; set; }
    }
}
