//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCVC_DTL_ERP
    {
        public decimal ID { get; set; }
        public decimal RCVC_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public decimal AMT { get; set; }
        public string CURN_CODE { get; set; }
        public Nullable<decimal> FCRATE { get; set; }
        public string CC_CODE { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
        public string CHEQUE_NO { get; set; }
        public Nullable<decimal> CHEQUE_REF { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<decimal> BANK_ID { get; set; }
        public string FUND_CODE { get; set; }
        public string CHECK_ACCOUNT_NO { get; set; }
        public Nullable<decimal> BOX_ID { get; set; }
        public Nullable<decimal> CHEQUE_BANK_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ACCOUNT_BANK_ERP ACCOUNT_BANK_ERP { get; set; }
        public virtual BANK_HERP BANK_HERP { get; set; }
        public virtual COLLECTORS_BOXES_ERP COLLECTORS_BOXES_ERP { get; set; }
        public virtual CURN CURN { get; set; }
        public virtual FUND FUND { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual RCVC_ERP RCVC_ERP { get; set; }
    }
}
