//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_VIEWS
    {
        public decimal ID { get; set; }
        public string STAFF_CODE { get; set; }
        public Nullable<decimal> VIEW_ID { get; set; }
        public string CAN_VIEW { get; set; }
        public string CAN_EDIT { get; set; }
        public string CAN_DELETE { get; set; }
        public string CAN_ADD { get; set; }
    
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        public virtual VIEWS VIEWS { get; set; }
    }
}
