//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAKEHOLDERS_ACCOUNTS_ERP
    {
        public decimal STAKEHOLDER_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public decimal ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP { get; set; }
    }
}
