//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAKEHOLDER_EMPLOYEES_ERP
    {
        public decimal ID { get; set; }
        public decimal STAKEHOLDER_ID { get; set; }
        public decimal EMPLOYEE_ID { get; set; }
    
        public virtual EMPLOYEE_HERP EMPLOYEE_HERP { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP { get; set; }
    }
}
