//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAKEHOLDERS_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAKEHOLDERS_ERP()
        {
            this.CHEQUES_DATA_ERP = new HashSet<CHEQUES_DATA_ERP>();
            this.CRNOTES_DTL_ERP = new HashSet<CRNOTES_DTL_ERP>();
            this.CRNOTES_MAS_ERP = new HashSet<CRNOTES_MAS_ERP>();
            this.JOURNAL_DETAILS = new HashSet<JOURNAL_DETAILS>();
            this.STAKEHOLDER_EMPLOYEES_ERP = new HashSet<STAKEHOLDER_EMPLOYEES_ERP>();
            this.STAKEHOLDERS_ACCOUNTS_ERP = new HashSet<STAKEHOLDERS_ACCOUNTS_ERP>();
            this.STAKEHOLDERS_RELATING_ERP = new HashSet<STAKEHOLDERS_RELATING_ERP>();
            this.STAKEHOLDERS_RELATING_ERP1 = new HashSet<STAKEHOLDERS_RELATING_ERP>();
            this.TRANS = new HashSet<TRANS>();
            this.DRNOTES_DTL_ERP = new HashSet<DRNOTES_DTL_ERP>();
            this.DRNOTES_MAS_ERP = new HashSet<DRNOTES_MAS_ERP>();
            this.PYVC_ERP = new HashSet<PYVC_ERP>();
            this.PYVC_ERP1 = new HashSet<PYVC_ERP>();
            this.RCVC_ERP = new HashSet<RCVC_ERP>();
            this.ILTIZAM = new HashSet<ILTIZAM>();
        }
    
        public decimal ID { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> TYPE_ID { get; set; }
        public string AUTHORIZED_NO { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string LOGINSTAFF { get; set; }
        public string IS_SUPPLIER { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string INTERNATIONAL_CITY_CODE { get; set; }
        public string IS_CITIZEN { get; set; }
        public string IDNO { get; set; }
        public Nullable<decimal> DEDUCTION_TYPE_ID { get; set; }
        public string STAKEHOLDER_CODE { get; set; }
        public string INSTAGRAM { get; set; }
        public string TWITTER { get; set; }
        public string FACEBOOK { get; set; }
        public string ZIP_CODE { get; set; }
        public string REGION_CODE { get; set; }
        public string GIS_STREET_CODE { get; set; }
        public string GIS_BUILDING_CODE { get; set; }
        public string POBOX { get; set; }
        public string NOTES { get; set; }
        public string WEBSITE { get; set; }
        public string IS_INSTITUTION { get; set; }
        public string IS_ENGINEERING_OFFICE { get; set; }
        public string POSITION_NAME { get; set; }
        public Nullable<decimal> TABUO_APRTMENT { get; set; }
        public string TABUO_FLOOR { get; set; }
        public string TABUO_BUILDING { get; set; }
        public string APRTMENT_NO { get; set; }
        public string HOD_CODE { get; set; }
        public Nullable<decimal> HAY_ID { get; set; }
        public Nullable<decimal> LAND_ID { get; set; }
        public string IS_PY { get; set; }
        public string IS_RC { get; set; }
        public Nullable<decimal> OLD_PAYREC_CODE { get; set; }
        public string OLD_SUPPLIER_CODE { get; set; }
        public string OLD_ACCOUNT_NO { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<decimal> NO_OF_CARDS { get; set; }
        public string WEB_USER { get; set; }
        public string WEB_PASS { get; set; }
        public string AUTO_PASS { get; set; }
        public string IS_PUBLIC { get; set; }
        public string NEW_QR_CODE { get; set; }
        public string CAR_NUMBER { get; set; }
        public string NEW_QR_CODE2 { get; set; }
        public string CAR_NUMBER2 { get; set; }
        public string IS_PAYEE { get; set; }
        public Nullable<System.DateTime> AFFILIATION_YAER { get; set; }
        public string HOBBIES { get; set; }
        public string REFERENCES { get; set; }
        public string DECISION { get; set; }
        public string NUMBER_DECISION { get; set; }
        public Nullable<System.DateTime> DATE_DECISION { get; set; }
        public Nullable<System.DateTime> DATE_APPLICATION { get; set; }
        public string SMS_YEARLY { get; set; }
        public string NEW_ADDRESS { get; set; }
        public Nullable<decimal> SYS_STS_B2LQ61HRE9LQYT_W3J2YAL { get; set; }
        public Nullable<decimal> SYS_STS25Q9CMVB57R8W604IOAXBZ1 { get; set; }
        public Nullable<decimal> SYS_STS30YG2VHQUZOKV3QBHDBOB2N { get; set; }
        public Nullable<decimal> SYS_STSIXQ9MSG7MD9JFULEDA_60WG { get; set; }
        public Nullable<decimal> SYS_STSRR4LEPH_DXLMWYQ8_32JOX_ { get; set; }
        public Nullable<decimal> SYS_STSUZEZAHL942GDP_73C512OK2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEQUES_DATA_ERP> CHEQUES_DATA_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_DTL_ERP> CRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_MAS_ERP> CRNOTES_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_DETAILS> JOURNAL_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAKEHOLDER_EMPLOYEES_ERP> STAKEHOLDER_EMPLOYEES_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAKEHOLDERS_ACCOUNTS_ERP> STAKEHOLDERS_ACCOUNTS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAKEHOLDERS_RELATING_ERP> STAKEHOLDERS_RELATING_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAKEHOLDERS_RELATING_ERP> STAKEHOLDERS_RELATING_ERP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANS> TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_DTL_ERP> DRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_MAS_ERP> DRNOTES_MAS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_ERP> PYVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PYVC_ERP> PYVC_ERP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_ERP> RCVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM> ILTIZAM { get; set; }
    }
}
