//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS
    {
        public string TFUND_CODE { get; set; }
        public string TFN_CODE { get; set; }
        public string TACCOUNT_NO { get; set; }
        public string TCC_CODE { get; set; }
        public string TSC_CODE { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string VOUCHER_TYPE { get; set; }
        public decimal VOUCHER_NO { get; set; }
        public string REF2 { get; set; }
        public string TRANS_TYPE { get; set; }
        public string CURN_CODE { get; set; }
        public decimal CURN_AMOUNT { get; set; }
        public decimal LOCAL_AMOUNT { get; set; }
        public decimal FCRATE { get; set; }
        public string CHECK_NO { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string BANK { get; set; }
        public string DETAILS { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> REFPR_CODE { get; set; }
        public Nullable<decimal> REFCASH_CODE { get; set; }
        public Nullable<decimal> REFBANK_CODE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<long> EMP_NO { get; set; }
        public string OFUND_CODE { get; set; }
        public string OFS_CODE { get; set; }
        public string OFN_CODE { get; set; }
        public string OACCOUNT_NO { get; set; }
        public string OCC_CODE { get; set; }
        public string OPR_CODE { get; set; }
        public string OSC_CODE { get; set; }
        public Nullable<decimal> SANDOUK_ACT { get; set; }
        public Nullable<decimal> CHECK_ACT { get; set; }
        public string CHECKPULLED { get; set; }
        public string NDDB { get; set; }
        public Nullable<System.DateTime> POSTED_DATE { get; set; }
        public Nullable<decimal> CHECK_REFERENCE { get; set; }
        public decimal SEQ { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string STAFF_CODE { get; set; }
        public string MOWAZANA { get; set; }
        public Nullable<decimal> JODRATE { get; set; }
        public Nullable<System.DateTime> UDATE { get; set; }
        public string SALEHWORKED { get; set; }
        public Nullable<decimal> SALEHAMOUNT { get; set; }
        public Nullable<decimal> PR_NEW { get; set; }
        public Nullable<decimal> FS_NEW { get; set; }
        public Nullable<decimal> STAKEHOLDER_ID { get; set; }
        public string STAFF_ID { get; set; }
        public Nullable<decimal> L1 { get; set; }
        public string UNIT_ID { get; set; }
        public string TPR_CODE { get; set; }
        public string TFS_CODE { get; set; }
        public string FUND_TYPE_ID { get; set; }
        public string TAX_CODE { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
        public Nullable<decimal> CAR_NO { get; set; }
        public Nullable<decimal> SYS_STS16NPHVISKRXVXM0M1_K_3W8 { get; set; }
        public Nullable<decimal> SYS_STS29J_07HVZZ9ZHRS81J1EQQ2 { get; set; }
        public Nullable<decimal> SYS_STS6_THM9PZ12XGA7BU7EXA4AP { get; set; }
        public Nullable<decimal> SYS_STSBJUWUOIPV1GRNAVHX_L2_SP { get; set; }
        public Nullable<decimal> SYS_STSF2B_CXHL0J_4KGJJKLAQIKO { get; set; }
        public Nullable<decimal> SYS_STSJ__ZGVGK3_59BTPD_6M_UQI { get; set; }
        public Nullable<decimal> SYS_STSNNA6YR6MKYX7HTM_Q_MEA2B { get; set; }
        public Nullable<decimal> SYS_STSOW6YV_GF69WY2BD27DRNBAD { get; set; }
        public Nullable<decimal> SYS_STSZMAFL9XXQB_OETM4UHB1B67 { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual FUNDERS_ERP FUNDERS_ERP { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        public virtual STAKEHOLDERS_ERP STAKEHOLDERS_ERP { get; set; }
        public virtual UNITS_ERP UNITS_ERP { get; set; }
    }
}
