//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITS_ACCOUNTS_ERP
    {
        public decimal ID { get; set; }
        public string UNIT_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public decimal YEAR { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> SYS_STS1E0YE70DO8A4UNYZVI488F_ { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual UNITS_ERP UNITS_ERP { get; set; }
    }
}
