//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITS_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNITS_ERP()
        {
            this.CRNOTES_DTL_ERP = new HashSet<CRNOTES_DTL_ERP>();
            this.EMPLOYEE_HERP = new HashSet<EMPLOYEE_HERP>();
            this.JOURNAL_DETAILS = new HashSet<JOURNAL_DETAILS>();
            this.TRANS = new HashSet<TRANS>();
            this.UNITS_ACCOUNTS_ERP = new HashSet<UNITS_ACCOUNTS_ERP>();
            this.DRNOTES_DTL_ERP = new HashSet<DRNOTES_DTL_ERP>();
            this.RCVC_ERP = new HashSet<RCVC_ERP>();
            this.ILTIZAM_DETAILS = new HashSet<ILTIZAM_DETAILS>();
        }
    
        public string ID { get; set; }
        public string SECTION_CODE { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
        public string IS_VALID { get; set; }
        public string MANAGER_ID { get; set; }
        public Nullable<decimal> SECTION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRNOTES_DTL_ERP> CRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_HERP> EMPLOYEE_HERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNAL_DETAILS> JOURNAL_DETAILS { get; set; }
        public virtual MUN_CLASS_DTL_ERP MUN_CLASS_DTL_ERP { get; set; }
        public virtual SECTIONS_ERP SECTIONS_ERP { get; set; }
        public virtual STAFF_ERP STAFF_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANS> TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_ACCOUNTS_ERP> UNITS_ACCOUNTS_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRNOTES_DTL_ERP> DRNOTES_DTL_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCVC_ERP> RCVC_ERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILTIZAM_DETAILS> ILTIZAM_DETAILS { get; set; }
    }
}
