//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIEWS()
        {
            this.STAFF_VIEWS = new HashSet<STAFF_VIEWS>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string CONTROLLOER { get; set; }
        public Nullable<decimal> GROUP_ID { get; set; }
        public Nullable<decimal> MODULE_ID { get; set; }
        public string METHOD_NAME { get; set; }
        public Nullable<decimal> CONTROLLER_FK { get; set; }
        public string ON_MENU { get; set; }
        public string CAN_ADD { get; set; }
        public string CAN_EDIT { get; set; }
        public string CAN_DELETE { get; set; }
        public Nullable<decimal> SYS_STSGDX4ZARENTGVZLQ42D7_FSP { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
        public virtual MODULES MODULES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAFF_VIEWS> STAFF_VIEWS { get; set; }
        public virtual CONTROLLERS_TABLE_ERP CONTROLLERS_TABLE_ERP { get; set; }
    }
}
